---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-apache2-sites-enabled
  namespace: devops
data:
  000-default.conf: |
    <VirtualHost *:80>
        ProxyPreserveHost on
        ProxyRequests off
        ProxyVia off
        ProxyPass / http://jira-cluster:8080/
        ProxyPassReverse / http://jira-cluster:8080/
        <Proxy *>
            Require all granted
        </Proxy>
        <Location />
            Require all granted
        </Location>
    </VirtualHost>
