apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-lib-postgresql-data
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: var-lib-postgresql-data
  resources:
    requests:
      storage: 10Gi