apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-atlassian-application-data-jira
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 10Gi