apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-atlassian-application-data-jira-shared
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi