on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n testregistry5 -g testregistry5ad6d-rg --location "West US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n testregistry5 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n testregistry5 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n testregistry5 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: testregistry5.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "docker.io/library/alvistack/jira" -t testregistry5.azurecr.io/kstest:${{ github.sha }} --label dockerfile-path=docker.io/library/alvistack/jira
        docker push testregistry5.azurecr.io/kstest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_kstest_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ks_test9646 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ks_test9646`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ks_test9646
        container-registry-url: testregistry5.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: kstestdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ks_test9646
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          testregistry5.azurecr.io/kstest:${{ github.sha }}
        imagepullsecrets: |
          kstestdockerauth   
